### ISSUE TITLE
babble.tell does not generate a Block for decisions outside of evejs

### ISSUE THREAD

**Issue by thfrei** [enmasseio/evejs#5]
It took me quite a while to figure this out. It seems only possible to use a babble.then on an agent.decision, when you require the babble package from within evejs.
I guess somehow the connection is handled inside of babble.

`
var babble = require('./../node_modules/evejs/node_modules/babble');
`

I was about to make a pull request to remove the babble package from the package.json, but I am not sure, if it is the best approach, since then some tests might not work.

Btw: That was the error log:

> TypeError: Block expected as choice
    at Decision.addChoice (c:\Thomas\Projects\eve\eve-agents\node_modules\evejs\node_modules\babble\lib\block\Decision.js:136:11)
    at c:\Thomas\Projects\eve\eve-agents\node_modules\evejs\node_modules\babble\lib\block\Decision.js:84:10
    at Array.forEach (native)

**Comment by josdejong** [comment]
Thanks for reporting, I'm not yet sure what's going on here. How can I reproduce your issue?

**Comment by josdejong** [comment]
I've released a new version of babble and evejs, which probably adresses the cause of your issue
